services:
  backend:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: care_local
    env_file:
      - ./docker/.local.env
    volumes:
      - .:/app
    ports:
      - "9090:9000"
      - "9876:9876"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["bash", "scripts/start-dev.sh"]
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: care_local
    env_file:
      - ./docker/.local.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["bash", "scripts/celery-dev.sh"]
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - ./docker/.local.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5